suggestions-channel: 504128702871764992 # channel to post suggestions to
database: ./cfc_suggestions.db # database file
suggestions-logging-channel: 504128702871764992 # channel to log suggestions to
auth-token: "secret" # secret used for authenticating with cfc_suggestions
bot-token: "token" # discord token
port: "8080"
host: "127.0.0.1"
