version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cfc-forms"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mv8ngeobrljz"
s3_prefix = "cfc-forms"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
