AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: go1.x
    Handler: lambda
    Timeout: 10
    Environment:
      Variables:
        SUBMISSIONS_DATABASE: !Ref SubmissionsDatabase

Resources:
  SubmissionsDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: UUID
          AttributeType: S
      KeySchema:
        - AttributeName: UUID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  CreateSubmission:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/create_submission/
      Policies: AmazonDynamoDBFullAccess
      Events:
        CreateHandler:
          Type: HttpApi
          Properties:
            Path: '/submissions'
            Method: POST

  GetSubmission:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/get_submission/
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetHandler:
          Type: HttpApi
          Properties:
            Path: '/submissions/{uuid}'
            Method: GET

  SendSubmission:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/send_submission/
      Policies: AmazonDynamoDBFullAccess
      Events:
        SendHandler:
          Type: HttpApi
          Properties:
            Path: '/submissions/{uuid}/send'
            Method: POST

  DeleteSubmission:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/delete_submission/
      Policies: AmazonDynamoDBFullAccess
      Events:
        DeleteHandler:
          Type: HttpApi
          Properties:
            Path: '/submissions/{uuid}'
            Method: DELETE
